variables:
  functionName: progress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
- test
- deploy

test:
  stage: test
  image: node:8.11.3
  script:
  - npm install
  - npm test
  only:
    variables:
    - $SLACK_API_TOKEN
    - $SLACK_TEST_CONVERSATION_ID
    - $GITLAB_API_TOKEN
    - $GITLAB_PROJECT_ID

deploy:
  stage: deploy
  image: node:8.11.3
  script:
  - npm install -g serverless@1.28.0
  - serverless deploy --stage $STAGE_NAME
  only:
    variables:
    - $AWS_ACCESS_KEY_ID
    - $AWS_SECRET_ACCESS_KEY
    - $SLACK_API_TOKEN
    - $SLACK_CONVERSATION_ID
    - $GITLAB_API_TOKEN
    - $GITLAB_PROJECT_ID
    - $CRON_SCHEDULE
    - $STAGE_NAME
