variables:
  functionName: progress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

deploy:
  image: node:8.11.3
  script:
  - npm install
  - npm test
  - npm install -g serverless@1.28.0
  - serverless deploy
  only:
    variables:
    - $AWS_ACCESS_KEY_ID
    - $AWS_SECRET_ACCESS_KEY
    - $SLACK_API_TOKEN
    - $SLACK_CONVERSATION_ID
    - $GITLAB_API_TOKEN
    - $GITLAB_PROJECT_ID
