service: progress

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

package:
  include:
  - node_modules/**

functions:
  hello:
    handler: handler.uploadProgressCharts
    events:
    - schedule: cron(0 3 * * ? *)
    environment:
      SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
      SLACK_CONVERSATION_ID: ${env:SLACK_CONVERSATION_ID}
      GITLAB_API_TOKEN: ${env:GITLAB_API_TOKEN}
      GITLAB_PROJECT_ID: ${env:GITLAB_PROJECT_ID}

