version: 2
jobs:
  deploy:
    docker:
    - image: node:10.6.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - node-v1-{{ .Branch }}-
        - node-v1-
    - run: npm install
    - run: npm install -g serverless@1.28.0
    - run: serverless deploy
    - save_cache:
        paths:
        - node_modules/
        - /usr/local/lib/node_modules/
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
