version: 2
jobs:
  deploy:
    docker:
    - image: node:10.6.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - node-v1-{{ .Branch }}-
        - node-v1-
    - run: |
        if [ -z "$AWS_ACCESS_KEY_ID" \
             -o -z "$AWS_SECRET_ACCESS_KEY" \
             -o -z "$SLACK_API_TOKEN" \
             -o -z "$SLACK_CONVERSATION_ID" ]; then
          exit 0
        fi
        npm install
        npm install -g serverless@1.28.0
        serverless deploy
    - save_cache:
        paths:
        - node_modules/
        - /usr/local/lib/node_modules/
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
workflows:
  version: 2
  deploy:
    jobs:
    - deploy
